[phases.setup]
nixPkgs = ["python3", "gcc", "nodejs", "chromium"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt",
    ". /opt/venv/bin/activate && playwright install-deps chromium"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
